[Fix] 100GB Benchmarks proper results.
hyrise-mp-22-23/hyrise pull request #119
Opened 2023-02-27 14:41 UTC by rrcomtech

Prior behaviour: Benchmarks showed misleading results with numbers that looked too high.

![Figure_1](https://user-images.githubusercontent.com/50635122/221592977-51647109-e80e-432f-b232-46513f9bd5a8.png)

New Behaviour: Benchmarks are now showing more realistic numbers. Done by replacing the "new" setup method from 1cdd3018 with the one from efde94. 

![Figure_1](https://user-images.githubusercontent.com/50635122/221593540-ea59e1d7-26c8-477f-aebd-cce6249f727f.png)

2023-02-28 12:47 UTC, SanJSp approved these changes
Good job :) fine from my side, only would like to wait for Jan to see the changes as well :)

2023-03-01 10:45 UTC, Bouncner commented
> Prior behaviour: Benchmarks showed misleading results with numbers that looked too high.
> 
> ![Figure_1](https://user-images.githubusercontent.com/50635122/221592977-51647109-e80e-432f-b232-46513f9bd5a8.png)
> 
> New Behaviour: Benchmarks are now showing more realistic numbers. Done by replacing the "new" setup method from [1cdd301](https://github.com/hyrise-mp-22-23/hyrise/commit/1cdd301848b8ae2a5f4ffda120a88faa085d773e) with the one from efde94.
> 
> ![Figure_1](https://user-images.githubusercontent.com/50635122/221593540-ea59e1d7-26c8-477f-aebd-cce6249f727f.png)

I agree that the numbers no longer look "too suspicious", but do you consider the last graph really "more realistic"?  Why should the throughput decrease from 1 to 2 threads?

2023-03-01 10:45 UTC, Bouncner commented
Is it even possible to compare 1000 MB with a 10 MB measurement?

2023-03-10 14:18 UTC, SanJSp commented
I was not aware, that in the second graph we had only 10MB. We should compare 1000MB, can you create these Robert? Is this even still planned to be merged?

2023-03-29 13:24 UTC, phoeinx requested changes
>I agree that the numbers no longer look "too suspicious", but do you consider the last graph really "more realistic"? Why should the throughput decrease from 1 to 2 threads?

Before we merge - has someone had the opportunity to address this question?

Also - if I understand correctly this PR changes the functionality back to every time creating new benchmarking files. What is the impact of this / is this the final conclusion (100% fine if yes, just want to make sure)

2023-03-31 13:49 UTC, phoeinx commented
@rrcomtech Is this pr already contained in the already merge FILE IO PR or do we still need to update/merge this?

2023-03-31 13:53 UTC, rrcomtech commented
AFAIK this was manually copied to #89. This can be closed.

2023-03-31 13:53 UTC, closed without merging